# Generated by Django 5.0.1 on 2024-01-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0028_remove_supplier_invoice_payment_supplier_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_type',
            fields=[
                ('payment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'bank_transfer'), ('other', 'other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_company_name', models.CharField(max_length=255)),
                ('supplier_contact_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=255)),
                ('supplier_region', models.CharField(max_length=255)),
                ('supplier_postal_code', models.CharField(max_length=10)),
                ('supplier_city', models.CharField(max_length=255)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('supplier_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='supplier_invoice',
            fields=[
                ('supplier_invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_invoice_number', models.CharField(max_length=200)),
                ('supplier_invoice_date', models.DateField()),
                ('supplier_invoice_amount_due', models.FloatField()),
                ('supplier_invoice_image_data', models.BinaryField()),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_invoice_item',
            fields=[
                ('supplier_invoice_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_invoice_item_quantity', models.IntegerField()),
                ('supplier_invoice_item_price', models.FloatField()),
                ('supplier_invoice_item_discount', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplier_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.supplier_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_invoice_payment',
            fields=[
                ('supplier_invoice_payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_invoice_payment_date', models.DateField()),
                ('supplier_invoice_payment_amount', models.FloatField()),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm.payment_type')),
                ('supplier_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.supplier_invoice')),
            ],
        ),
    ]
