# Generated by Django 5.0.1 on 2024-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_company_name',
            new_name='supplier_name',
        ),
    ]
