# Generated by Django 5.0 on 2023-12-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_subfamily_id_alter_product_supplier_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="subfamily_id",
            new_name="subfamily",
        ),
    ]
