# Generated by Django 5.0 on 2023-12-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_rename_subfamily_id_product_subfamily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="family_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sub_family",
            name="subfamily_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
