# Generated by Django 5.0 on 2024-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_family_family_id_alter_sub_family_subfamily_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="sub_family",
            new_name="subfamily",
        ),
    ]
