# Generated by Django 5.0 on 2024-01-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_family_id_alter_product_subfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.family'),
        ),
    ]
