# Generated by Django 5.0 on 2024-01-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_buy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_sell',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subfamily',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.subfamily'),
        ),
    ]
