# Generated by Django 5.0 on 2024-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_barcode_alter_product_product_price_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skuu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
