# Generated by Django 5.0 on 2024-01-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_skuu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skuu',
        ),
    ]
