# Generated by Django 5.0 on 2024-01-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
