# Generated by Django 5.0 on 2024-01-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
