# Generated by Django 5.0 on 2024-01-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
    ]
