# Generated by Django 5.0.1 on 2024-01-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_product_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_invoice_payment',
            name='supplier_invoice_id',
        ),
        migrations.RemoveField(
            model_name='supplier_invoice_item',
            name='supplier_invoice_id',
        ),
        migrations.RemoveField(
            model_name='supplier_invoice_item',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='supplier_invoice_payment',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='supplier_invoice',
        ),
        migrations.DeleteModel(
            name='supplier_invoice_item',
        ),
        migrations.DeleteModel(
            name='supplier_invoice_payment',
        ),
    ]
